name: focus_guide
description: 专注引导MVP - 温和引导替代强制阻止的移动应用

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0

  # 状态管理 (必需)
  provider: ^6.1.5

  # 本地存储 (必需)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.1
  
  # 权限管理 (必需)
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
  # Hive代码生成 (必需)
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true